<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CAAB91C" failures="1" tests="6" name="Test1" time="2.311" errors="0" timestamp="2021-02-03T00:07:35 PST">
  <testcase classname="restbasic1.restbasicRequest.DeleteRequest" name="delete_request" time="1.702"/>
  <testcase classname="restbasic1.restbasicRequest.getRequestValidation" name="getValidation_StatusCode" time="0.049"/>
  <testcase classname="restbasic1.restbasicRequest.getRequestValidation2" name="getValidation_ResponseBody" time="0.059">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at restbasic1.restbasicRequest.getRequestValidation2.getValidation_ResponseBody(getRequestValidation2.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- getValidation_ResponseBody -->
  <testcase classname="restbasic1.restbasicRequest.getRequest" name="getStatusCode" time="0.182"/>
  <testcase classname="restbasic1.restbasicRequest.getRequestValidation1" name="getValidation_ResponseHeader" time="0.051"/>
  <testcase classname="restbasic1.restbasicRequest.postRequest" name="creatUserTest" time="0.067"/>
</testsuite> <!-- Test1 -->
